from odoo import fields, models


class FacilityBookingConflict(models.Model):
    """Result of evaluating one constraint against one booking.

    Generated by ``facility.booking._evaluate_constraints``. It is the generic
    surface on which every constraint reports its violations, so that views,
    scoring and optimisation can consume them uniformly.
    """

    _name = "facility.booking.conflict"
    _description = "Booking Conflict"
    _order = "severity, weight desc"

    booking_id = fields.Many2one(
        "facility.booking", required=True, ondelete="cascade", index=True)
    constraint_id = fields.Many2one(
        "facility.constraint", required=True, ondelete="cascade")
    severity = fields.Selection(
        [("hard", "Hard (blocking)"), ("soft", "Soft (penalty)")],
        required=True)
    weight = fields.Integer(default=0)
    message = fields.Char(required=True)
